[project]
name = "chess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "google-genai>=1.38.0",
    "pygame>=2.6.1",
    "pygame-gui>=0.6.14",
]
